version: '3.8'

services:

  pg_mysqldb:
    image: ${MYSQL_IMAGE_NAME}
    container_name: pg_mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysqldb-data:/var/lib/mysql

  pg_backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: pg_backend
    restart: always
    ports:
      - "${API_PORT}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=pg_mysqldb;Port=3306;Database=GithubAnalyzeDB;Uid=root;Pwd=123456789Aa;
      - GithubConfig__Token=${GITHUB_TOKEN}
      - GithubConfig__Username=${GITHUB_USERNAME}
      - GithubConfig__BaseAddress=https://api.github.com
      - CorsConfig__Domains__0=http://localhost:${FE_PORT}
      - CorsConfig__PolicyName=AllowSpecificOrigins
    depends_on:
      - pg_mysqldb

  pg_frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - VITE_APP_API_URL=http://localhost:${API_PORT}/api
    container_name: pg_frontend
    restart: always
    ports:
      - "${FE_PORT}:80"
    depends_on:
      - pg_backend

volumes:
  mysqldb-data: